name: app
description: "Shojag app for safety and security"

publish_to: "none"

#version: 1.2.0+2 # for ios
version: 1.1.7+20 # for android

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3

  # for state management
  provider: ^6.1.5+1
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # for routing and navigation
  go_router: ^16.2.2

  # for localization
  intl:
  flutter_timezone: ^5.0.0

  email_validator: ^3.0.0
  url_launcher: ^6.3.2
  gap: ^3.0.1

  # for modeling and error handling
  equatable: ^2.0.7
  fpdart: ^1.1.1

  # for file system
  path_provider: ^2.1.5
  path: ^1.9.1
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0

  # for api call
  dio: ^5.9.0
  connectivity_plus: ^7.0.0

  # for local database and cache
  sqlite3_flutter_libs: ^0.5.39
  sqlite3: ^2.9.0
  drift: ^2.28.2
  drift_flutter: ^0.2.7

  hive_ce: ^2.13.2
  hive_ce_flutter: ^2.3.2

  # for dependency injection
  get_it: ^8.2.0

  # image and media
  flutter_svg: ^2.2.1
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.4.1

  screenshot: ^3.0.0

  google_fonts: ^6.3.1

  dropdown_button2: ^2.3.9
  animated_toggle_switch: ^0.8.5
  flutter_typeahead: ^5.2.0
  pinput: ^5.0.2
  timeago: ^3.7.1
  float_column: ^4.0.3
  dropdown_search: ^6.0.2

  # for logging
  logger: ^2.6.1

  # animation and effects
  lottie: ^3.3.2
  flutter_animate: ^4.5.2
  animations: ^2.0.11
  modal_bottom_sheet: ^3.0.0
  dotted_line: ^3.2.3
  photo_view: ^0.15.0
  styled_text: ^8.1.0
  custom_refresh_indicator: ^4.0.1
  skeletonizer: ^2.1.0+1
  #  tutorial_coach_mark:
  #    path: /Users/supreoxlimited2/StudioProjects/package-update/tutorial_coach_mark-1.2.13
  tutorial_coach_mark:
    git:
      url: https://github.com/SamratAlShahriar/tutorial_coach_mark.git
      ref: main

  share_plus: ^12.0.0



  # for image and video
  image_picker: ^1.2.0
  image_cropper: ^10.0.0+1
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4

  # for playing video
  video_player: ^2.10.0

  # for geolocation and location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  background_location_tracker: ^1.6.1

  # for map
  mapbox_maps_flutter: ^2.11.0
  latlong2: ^0.9.1

  font_awesome_flutter: ^10.10.0
  super_tooltip: ^2.1.0

  # firebase service
  firebase_core: ^4.1.0

  # for fcm notification
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2

  # firebase analytics
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1

  # for socket io
  #socket_io_client: ^3.0.2

  # for contacts
  flutter_contacts: ^1.1.9+2

  # for payment gateway integration
  #  flutter_sslcommerz:
  #    path: /Users/supreoxlimited2/StudioProjects/package-update/flutter_sslcommerz-2.3.6
  flutter_sslcommerz:
    git:
      url: https://github.com/SamratAlShahriar/flutter_sslcommerz.git
      ref: main

  # for periodic task
  workmanager: ^0.9.0+3

  # app upgrader
  upgrader: ^12.1.0
  record: ^6.1.1
  just_audio: ^0.10.5

  # pusher channel
  # pusher_channels_flutter: ^2.5.0
  #  pusher_channels_flutter:
  #    git:
  #      url: https://github.com/kishormainali/pusher-channels-flutter.git
  #      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5

  # generators
  hive_ce_generator: ^1.9.2
  #riverpod_generator: ^2.6.5
  drift_dev: ^2.28.0
  build_runner: ^2.7.1

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/temp/icon_1024x1024x512.png"
  adaptive_icon_foreground: "assets/temp/icon_1024x1024x600_transparent.png"
  adaptive_icon_background: "assets/temp/icon_background_1024x1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/temp/splash_1024x1024x512_transparent.png"
  image_dark: "assets/temp/splash_1024x1024x512_transparent.png"

  android_12:
    color: "#ffffff"
    color_dark: "#000000"
    image: "assets/temp/splash_12_1152x1152x768_transparent.png"
    image_dark: "assets/temp/splash_12_1152x1152x768_transparent.png"

  android: true
  ios: true

  fullscreen: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/background/
    - assets/icon/
    - assets/logo/
    - assets/lottie/
    - assets/temp/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


flutter_intl:
  enabled: true
