// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:app/shared/data/model/session_area_radius_model.dart';
import 'package:app/shared/data/model/session_auth_model.dart';
import 'package:app/shared/data/model/session_language_model.dart';
import 'package:app/shared/data/model/session_list_sort_type_model.dart';
import 'package:app/shared/data/model/session_location_lat_lng_model.dart';
import 'package:app/shared/data/model/session_notification_settings_model.dart';
import 'package:app/shared/data/model/session_premium_service_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SessionAreaRadiusModelAdapter());
    registerAdapter(SessionAuthModelAdapter());
    registerAdapter(SessionLanguageModelAdapter());
    registerAdapter(SessionListSortTypeModelAdapter());
    registerAdapter(SessionLocationLatLngModelAdapter());
    registerAdapter(SessionNotificationSettingsModelAdapter());
    registerAdapter(SessionPremiumServiceModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SessionAreaRadiusModelAdapter());
    registerAdapter(SessionAuthModelAdapter());
    registerAdapter(SessionLanguageModelAdapter());
    registerAdapter(SessionListSortTypeModelAdapter());
    registerAdapter(SessionLocationLatLngModelAdapter());
    registerAdapter(SessionNotificationSettingsModelAdapter());
    registerAdapter(SessionPremiumServiceModelAdapter());
  }
}
